name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1 Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2 Setup Node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3 Install dependencies
    - name: Install dependencies
      run: npm install

    # 4 Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # 5 Run Playwright tests
    - name: Run Playwright Tests
      run: npx playwright test tests/test.spec.js 

    # 6 Upload Allure raw results
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results

    # 7 Generate Allure HTML Report
    - name: Generate Allure Report
      run: |
        npm install -g allure-commandline --save-dev
        allure generate allure-results --clean -o allure-report

    # 8 Upload Allure HTML Report
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

